services:
  banking-service:
    build: .
    container_name: banking-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:///./banking.db
    volumes:
      - .:/app
    restart: always